const homeRel = (p: string, home: string) => (p.toLowerCase().startsWith(home.toLowerCase()) ? "$env:USERPROFILE" + p.slice(home.length) : p);

export const renderPs1 = (o: { baseUrl: string; mcpBundle: string; home: string }) => `# claude-gw — generated by boot-slapper; edits are overwritten on \`bs onboard\`.
# Claude Code against the gateway at ${o.baseUrl}. Secrets come from Windows Credential Manager (bs secrets set <service>).
function claude-gw {
  [void][Windows.Security.Credentials.PasswordVault,Windows.Security.Credentials,ContentType=WindowsRuntime]
  $v = New-Object Windows.Security.Credentials.PasswordVault
  $acct = $env:USERNAME
  try { $c = $v.Retrieve('cornell-ai-gateway', $acct); $c.RetrievePassword(); $gw = $c.Password }
  catch { Write-Error "claude-gw: no gateway token in Credential Manager (resource 'cornell-ai-gateway'). Run: bs secrets set cornell-ai-gateway"; return }
  $mecp = ''
  try { $c = $v.Retrieve('mecp-device-token', $acct); $c.RetrievePassword(); $mecp = $c.Password }
  catch { Write-Warning "claude-gw: no MeCP device token — mecp tools will 401. Run: bs secrets set mecp-device-token" }
  $names = 'ANTHROPIC_BASE_URL','ANTHROPIC_AUTH_TOKEN','CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS','DISABLE_TELEMETRY','MECP_DEVICE_TOKEN'
  $saved = @{}
  foreach ($n in $names) { $saved[$n] = [Environment]::GetEnvironmentVariable($n, 'Process') }
  $env:ANTHROPIC_BASE_URL = '${o.baseUrl}'
  $env:ANTHROPIC_AUTH_TOKEN = $gw
  $env:CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS = '1'
  $env:DISABLE_TELEMETRY = '1'
  $env:MECP_DEVICE_TOKEN = $mecp
  try { & claude --mcp-config "${homeRel(o.mcpBundle, o.home)}" @args }
  finally { foreach ($n in $names) { [Environment]::SetEnvironmentVariable($n, $saved[$n], 'Process') } }
}
`;

/** \`claude-gw-run\` — entry point invoked by \`claude-gw.cmd\` via \`-File\`; dot-sources the function then calls it with the forwarded args. */
export const renderRunnerPs1 = () => "# claude-gw-run — generated by boot-slapper; entry point for claude-gw.cmd.\n. \"$env:USERPROFILE\\.config\\boot-slapper\\claude-gw.ps1\"\nclaude-gw @args\n";

/** cmd shim so \`claude-gw\` also works from Git Bash / cmd. Runs claude-gw-run.ps1 via -File, so args (including quoted/quote-heavy ones) pass through verbatim. */
export const renderCmd = () => `@echo off\r\npowershell -NoProfile -ExecutionPolicy Bypass -File "%USERPROFILE%\\.config\\boot-slapper\\claude-gw-run.ps1" %*\r\n`;
