const homeRel = (p: string, home: string) => (p.startsWith(home) ? "$HOME" + p.slice(home.length) : p);

export const renderZsh = (o: { baseUrl: string; mcpBundle: string; home: string }) => `# claude-gw — generated by boot-slapper; edits are overwritten on \`bs onboard\`.
# Claude Code against the gateway at ${o.baseUrl}, with the launch-scoped MCP bundle.
# Secrets come from the login Keychain (bs secrets set <service>); nothing sensitive sits in a file.
# Open Brain carries no token: Claude Code runs its OAuth flow once via /mcp -> openbrain.
# Deliberately NOT --strict-mcp-config: project .mcp.json servers must survive.

claude-gw() {
  local gw_token mecp_token
  gw_token=$(security find-generic-password -w -s cornell-ai-gateway -a "$USER" 2>/dev/null)
  if [[ -z "$gw_token" ]]; then
    print -u2 "claude-gw: no gateway token in Keychain (service 'cornell-ai-gateway'). Run: bs secrets set cornell-ai-gateway"
    return 1
  fi
  mecp_token=$(security find-generic-password -w -s mecp-device-token -a "$USER" 2>/dev/null)
  if [[ -z "$mecp_token" ]]; then
    print -u2 "claude-gw: no MeCP device token in Keychain — mecp tools will 401. Run: bs secrets set mecp-device-token"
  fi
  # No ANTHROPIC_MODEL pin: let the gateway serve its default; pass --model explicitly when needed.
  ANTHROPIC_BASE_URL="${o.baseUrl}" \\
  ANTHROPIC_AUTH_TOKEN="$gw_token" \\
  CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1 \\
  DISABLE_TELEMETRY=1 \\
  MECP_DEVICE_TOKEN="$mecp_token" \\
  command claude --mcp-config "${homeRel(o.mcpBundle, o.home)}" "$@"
}
`;
