import { bsDir } from "../../engine/desktop.ts";
import { pj, type Os } from "../../engine/env.ts";
import { assertSafeRef, type SecretService } from "../../engine/secrets/store.ts";

/** Helper executables Claude Desktop runs to obtain a credential (inferenceCredentialHelper / headersHelper).
 *  darwin/linux: POSIX sh; win32: PowerShell (Desktop runs .ps1 through powershell.exe -File). Paths must be absolute and contain no `"` or `%`. */
export const HELPER_MODE = 0o700;
export const helperPath = (os: Os, home: string, name: string) => pj(os, bsDir(os, home), `${name}${os === "win32" ? ".ps1" : ".sh"}`);

const HEADER_SAFE = /^[A-Za-z0-9-]+$/;
const PREFIX_SAFE = /^[^'"$`\\{}\x00-\x1f\x7f]*$/;

/** service (and account, when given) via the same guard `bs secrets set` uses before a value ever reaches a shell/PowerShell literal. */
function checkService(service: SecretService, account?: string): void {
  assertSafeRef({ service, account: account ?? "a" });
}
function checkHeader(header: string): void {
  if (!HEADER_SAFE.test(header)) throw new Error(`header contains characters outside [A-Za-z0-9-]: ${JSON.stringify(header)}`);
}
function checkPrefix(prefix: string): void {
  if (!PREFIX_SAFE.test(prefix)) throw new Error(`prefix contains an unsafe character (one of ' " $ backtick \\ { } or a control character): ${JSON.stringify(prefix)}`);
}

const HEAD_SH = (what: string) => `#!/bin/sh\n# ${what} — generated by boot-slapper; edits are overwritten on \`bs onboard\`.\n# Claude Desktop runs this helper to obtain the value at session start; nothing sensitive sits in a config file.\n`;
const HEAD_PS = (what: string) => `# ${what} — generated by boot-slapper; edits are overwritten on \`bs onboard\`.\n# Claude Desktop runs this helper (powershell.exe -File) to obtain the value at session start.\n$ErrorActionPreference = 'Stop'\n[void][Windows.Security.Credentials.PasswordVault,Windows.Security.Credentials,ContentType=WindowsRuntime]\n$v = New-Object Windows.Security.Credentials.PasswordVault\n`;

/** `bs secrets set`'s account: an explicit safe-charset literal, else resolved at runtime the same order as `defaultAccount` (USER, then USERNAME). */
const darwinAccountArg = (account?: string) => (account ? `'${account}'` : `"\${USER:-$USERNAME}"`);
const win32AccountResolve = (account?: string) => (account ? "" : "$acct = if ($env:USER) { $env:USER } else { $env:USERNAME }\n");
const win32AccountArg = (account?: string) => (account ? `'${account}'` : "$acct");

const readSh = (os: Os, service: SecretService, account?: string) =>
  os === "darwin" ? `security find-generic-password -w -s ${service} -a ${darwinAccountArg(account)}` : `cat "$HOME/.config/boot-slapper/secrets/${service}"`;

/** Prints the secret's value and nothing else (Desktop reads stdout as a bare token). */
export function renderCredentialHelper(os: Os, service: SecretService, account?: string): string {
  checkService(service, account);
  if (os === "win32") {
    return HEAD_PS(`${service} credential helper`) + win32AccountResolve(account) + `$c = $v.Retrieve('${service}', ${win32AccountArg(account)}); $c.RetrievePassword()\n[Console]::Out.Write($c.Password)\n`;
  }
  return HEAD_SH(`${service} credential helper`) + `exec ${readSh(os, service, account)}\n`;
}

/** Prints a flat JSON header map (Desktop's headersHelper contract). The value is not JSON-escaped: every service here issues URL-safe tokens. */
export function renderHeadersHelper(os: Os, service: SecretService, header: string, prefix: string, account?: string): string {
  checkService(service, account);
  checkHeader(header);
  checkPrefix(prefix);
  if (os === "win32") {
    return HEAD_PS(`${service} headers helper`) + win32AccountResolve(account) + `$c = $v.Retrieve('${service}', ${win32AccountArg(account)}); $c.RetrievePassword()\n[Console]::Out.Write('{"${header}":"${prefix}' + $c.Password + '"}')\n`;
  }
  return HEAD_SH(`${service} headers helper`) + `t=$(${readSh(os, service, account)}) || exit 1\n[ -n "$t" ] || exit 1\nprintf '{"%s":"%s%s"}\\n' '${header}' '${prefix}' "$t"\n`;
}
