import { bsDir } from "../../engine/desktop.ts";
import { pj, type Os } from "../../engine/env.ts";
import type { SecretService } from "../../engine/secrets/store.ts";

/** Helper executables Claude Desktop runs to obtain a credential (inferenceCredentialHelper / headersHelper).
 *  darwin/linux: POSIX sh; win32: PowerShell (Desktop runs .ps1 through powershell.exe -File). Paths must be absolute and contain no `"` or `%`. */
export const HELPER_MODE = 0o700;
export const helperPath = (os: Os, home: string, name: string) => pj(os, bsDir(os, home), `${name}${os === "win32" ? ".ps1" : ".sh"}`);

const HEAD_SH = (what: string) => `#!/bin/sh\n# ${what} — generated by boot-slapper; edits are overwritten on \`bs onboard\`.\n# Claude Desktop runs this helper to obtain the value at session start; nothing sensitive sits in a config file.\n`;
const HEAD_PS = (what: string) => `# ${what} — generated by boot-slapper; edits are overwritten on \`bs onboard\`.\n# Claude Desktop runs this helper (powershell.exe -File) to obtain the value at session start.\n$ErrorActionPreference = 'Stop'\n[void][Windows.Security.Credentials.PasswordVault,Windows.Security.Credentials,ContentType=WindowsRuntime]\n$v = New-Object Windows.Security.Credentials.PasswordVault\n`;

const readSh = (os: Os, service: SecretService) =>
  os === "darwin" ? `security find-generic-password -w -s ${service} -a "$USER"` : `cat "$HOME/.config/boot-slapper/secrets/${service}"`;

/** Prints the secret's value and nothing else (Desktop reads stdout as a bare token). */
export function renderCredentialHelper(os: Os, service: SecretService): string {
  if (os === "win32") return HEAD_PS(`${service} credential helper`) + `$c = $v.Retrieve('${service}', $env:USERNAME); $c.RetrievePassword()\n[Console]::Out.Write($c.Password)\n`;
  return HEAD_SH(`${service} credential helper`) + `exec ${readSh(os, service)}\n`;
}

/** Prints a flat JSON header map (Desktop's headersHelper contract). The value is not JSON-escaped: every service here issues URL-safe tokens. */
export function renderHeadersHelper(os: Os, service: SecretService, header: string, prefix: string): string {
  if (os === "win32") return HEAD_PS(`${service} headers helper`) + `$c = $v.Retrieve('${service}', $env:USERNAME); $c.RetrievePassword()\n[Console]::Out.Write('{"${header}":"${prefix}' + $c.Password + '"}')\n`;
  return HEAD_SH(`${service} headers helper`) + `t=$(${readSh(os, service)}) || exit 1\n[ -n "$t" ] || exit 1\nprintf '{"%s":"%s%s"}\\n' '${header}' '${prefix}' "$t"\n`;
}
